### ISSUE TITLE
(epic) Get off of Robinhood package

### ISSUE THREAD

**Issue by westonplatter** [westonplatter/simple_metrics#4]
Todos:
- [x] fetch.fetch_json_by_url
- [x] fetch.stock_orders
- [x] fetch.option_orders
- [x] fetch.positions
- [x] fetch.option_positions
